### PR TITLE
Add tests that ensure parameter & input orders are retained

### PR DESCRIPTION
**Pull request by akx**

### CODE REVIEW

**Comment by ruksi** [comment]
do we need to consider ourselves with the parameter groups; sorting of those and inside of those?

**Comment by akx** [comment]
@ruksi Parameter categories are just a string on a Parameter object, they don't have an intrinsic ordering (and as is, can't have one).

**Comment by ruksi** [comment]
so a strong **no**

**Review by ruksi — APPROVED** [review]
lgtm!

**Pull request merged**
