### PR TITLE
Simple default config merging + ability to provide custom merging strategy

### PR DESCRIPTION
**Pull request by JuhaKiili**
Some ancient WIP commits are left in as-is for now to separate different authors (might help with review).

### CODE REVIEW

**Review by akx — APPROVED** [review]
@JuhaKiili Looks good – I assume you've tested the semantics of the default merges.

I've

* rebased this on top of the current `master`
* squashed some flip-flop commits (that added tests, then removed them) 
* removed the unused `to_yaml()` function from the last commit, since it was never even tested or anything.

**Comment by JuhaKiili** [comment]
> @JuhaKiili Looks good – I assume you've tested the semantics of the default merges.
> 
> I've
> 
> * rebased this on top of the current `master`
> * squashed some flip-flop commits (that added tests, then removed them)
> * removed the unused `to_yaml()` function from the last commit, since it was never even tested or anything.

**Comment by JuhaKiili** [comment]
> @JuhaKiili Looks good – I assume you've tested the semantics of the default merges.
> 
> I've
> 
> * rebased this on top of the current `master`
> * squashed some flip-flop commits (that added tests, then removed them)
> * removed the unused `to_yaml()` function from the last commit, since it was never even tested or anything.

The `to_yaml()` is used by the other PR in `valohai-utils`!

**Comment by akx** [comment]
> The `to_yaml()` is used by the other PR in `valohai-utils`! [valohai/valohai-utils#23](https://github.com/valohai/valohai-utils/pull/23)
> 
> I should add tests for it?

I think it should belong in another PR, or preferably maybe in `valohai-utils` itself. `valohai-yaml` hasn't been involved in serializing the parsed config _to_ YAML yet.

**Review by akx — APPROVED** [review]
Approving w/o the `to_yaml` stuff. :)

**Pull request merged**
